# Generated by Django 3.1.12 on 2021-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='Ninguno', max_length=200)),
                ('email', models.CharField(default='Ninguno', max_length=100)),
                ('telefono', models.CharField(default='Ninguno', max_length=15)),
                ('mensaje', models.TextField(default='')),
                ('isAtendido', models.BooleanField(default=False)),
                ('respuesta', models.TextField(default='')),
            ],
            options={
                'db_table': 'datos_correo',
                'ordering': ['-id'],
            },
        ),
    ]
