# Generated by Django 3.1.12 on 2021-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpleo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='uIsGraduado',
            new_name='uniIsGraduado',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numInterior',
            field=models.CharField(db_column='num_interior', max_length=10),
        ),
    ]
