# Generated by Django 3.1.12 on 2021-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpleo', '0003_auto_20210818_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='posicionDeseada',
            field=models.CharField(choices=[('Server/Gaucho', 'Server/Gaucho'), ('Bartender', 'Bartender'), ('Prep/Line Cook', 'Prep/Line Cook'), ('Administrative', 'Administrative'), ('Server Assistant', 'Server Assistant'), ('Hostess/Cashier', 'Hostess/Cashier'), ('Dishwasher', 'Dishwasher')], db_column='posicion_deseada', max_length=25),
        ),
    ]
